import torch
import soundfile as sf
import gc
from qwen_tts import Qwen3TTSModel

text = "Hi, My name is tom hank. I am here to tell you that I am super excited!!!! to show Qwen3 TTS Demo. The audio is automatically generated by an AI model solely to demonstrate the model's capacity."
ref_audio = "./reference.wav"
ref_text  = "if you have to get past any sense of self cannot care what you look like or what you sound like you cannot care if you are sounding"
speaker = "tomhanks"  # Change this to your speaker Name

def test_base_model():
    print("=== Testing Base Model ===")
    model = Qwen3TTSModel.from_pretrained(
        "Qwen/Qwen3-TTS-12Hz-1.7B-Base",
        device_map="cuda:0",
        dtype=torch.bfloat16,
        attn_implementation="flash_attention_2",
    )
    
    print("Supported speakers for base model:", model.get_supported_speakers())
    
    # Run the user's example
    print("Generating voice clone with base model...")
    wavs, sr = model.generate_voice_clone(
        text=text,
        language="English",
        ref_audio=ref_audio,
        ref_text=ref_text,
    )
    sf.write("output_base_model_voice_clone.wav", wavs[0], sr)
    print("Saved output_base_model_voice_clone.wav")
    
    del model
    torch.cuda.empty_cache()
    gc.collect()
    print("Base model removed from memory.\n")

def test_finetuned_model_standard():
    print("=== Testing Finetuned Model (Standard Custom Voice) ===")
    # Using the latest checkpoint in output2-e6
    finetuned_path = "./output2-e6/checkpoint-epoch-23"
    print(f"Loading finetuned model from {finetuned_path}...")
    model = Qwen3TTSModel.from_pretrained(
        finetuned_path,
        device_map="cuda:0",
        dtype=torch.bfloat16,
        attn_implementation="flash_attention_2",
    )
    
    print("Supported speakers for finetuned model:", model.get_supported_speakers())
    
    try:
        print(f"Generating custom voice with finetuned model using speaker '{speaker}'...")
        wavs, sr = model.generate_custom_voice(
            text=text,
            language="English",
            speaker=speaker,
        )
        sf.write("output_finetuned_custom_voice.wav", wavs[0], sr)
        print("Saved output_finetuned_custom_voice.wav")
    except Exception as e:
        print(f"Error generating custom voice: {e}")
        
    return model

def test_finetuned_model_zero_shot(model):
    print("=== Testing Finetuned Model (Zero Shot) ===")
    
    print("Generating voice clone with finetuned model...")
    wavs, sr = model.generate_voice_clone(
        text=text,
        language="English",
        ref_audio=ref_audio,
        ref_text=ref_text,
    )
    sf.write("output_finetuned_voice_clone.wav", wavs[0], sr)
    print("Saved output_finetuned_voice_clone.wav")
    
    del model
    torch.cuda.empty_cache()
    gc.collect()
    print("Finetuned model removed from memory.\n")

if __name__ == "__main__":
    test_base_model()
    model = test_finetuned_model_standard()
    test_finetuned_model_zero_shot(model)
